# `r emo::ji("police_officer")` Air Law {#air-law}

## Licensing

An instrument rating shall be valid for 1 year. An instrument rating shall be revalidated within 3 months. If instrument rating has not been revalidated within 7 years, need to repeat theory.

Applicants for IR need 50 hours cross-country flight as PIC with at least 10 hour in the relevant aircraft category.

## Rules of the air

### Emergency

Transponder mode A, Squawk 7700

### Communication failure

- VFR: Squawk 7600 and land at nearest suitable airport
- IFR in VMC: Continue VFR and land directly
- IFR in IMC: Follow flight plan and land within 30 minutes of ETA
  - no radar: last assigned speed / level for 20 minutes
  - radar: last assigned speed / level for 20 minutes
  
### Reporting point

- Aircraft ident
- Position
- Time
- Altitude
- Next position
- Ensuing point

Memory rule: APTANE (all pilot take aircraft navigation exams)

### Intrument flight rules

RVSM airspace vertical separations:

> Add image.

- < FL 290: 1000 ft 
- FL 290 - FL 410
  - in RVSM: 1000 ft
  - else: 2000 ft (standard)
- > FL 410: 2000 ft

Semi-circular rules:

> Add image.

0 - 179 degree magnetic: ODD
180 - 359 degree magnetic: EVEN

Minimum flight level:

- 600 m (2000 ft) above highest obstacle within 8 km in mountainous areas
- elsewhere 300 m (1000 ft)

### Holding procedures

Turns: right (standard)

Outbound time:
- below 14.000 ft: 1min
- above 14.000 ft: 1,5 min

Bank:
25 degree or 3 degree per second (whichever is less)

Buffer area: 5NM

Entry procedures:

> Add image.

Memory rule: The name of the holding procedure describes the flight path after the holding fix.

Minimum permissible holding height: 300 m obstc. clearance

Shuttle: climb / descend in holding

adapt timing (tail/headwind) and heading (wind correction angle) to maintain the track

### Altimeter settings

> Add image of Transition level / layer / altitude

Transition altitude not less than 3000 ft AGL

Calculated height of transition altitude rounded up to next full 1000 ft
Transition altitudes are published in AIPs or SIDs

## Aircraft operations

### Departure 

Obstacle clearance method for departues with no track guidance:

- omnidirectional: restricted sectors specified by bearings and distances

- straight (< 15 degree): track guidance within 20km

- turn (> 15 track): guidance within 10km

Minimum obstacle clearance: 0.8% of horizontal distance in straight departures

Procedure design gradient: 2.5% (at least) + 0,8% (additional margin) = 3,3%

### Approach

MOC:
- initial: 300m (1000 ft)
- intermediate: 150m (500 ft)
- final: 90m (300ft) without FAF and 75m (250ft) with FAF

OCA/H: Obstacle clearance altitude/height
DA/H: decision altitude/height = OCA/H + margin
MDA/H: for non-precision: Minimum descend A/H = OCA/H + margin

Segments: arrival, initial, intermediate, final, missed approach

Aircraft categories based on $V_{AT}$ (IAS at threshold): ...

> Image of approach and missed approach segments

Optimum glide path 3 degree / 5 percent

Circling approach.

## Air traffic management

Calculate transition level from transition altitude (will be passed to aircraft by ATS):
TA: 3000 ft, QNH: 990 hPa, (1013 hPa - 990 hPa) * 30 ft/hPa = 660 ft, hence if changing the altimeter reference at 3000 ft to standard pressure would have 3660 ft altitude, hence TL is 4000 ft = FL 40.

2D separation: horizontal and vertical

Longitudinal separation minima:

- on track: 5 (3) min if proceeding aircraft is 20 kts (40kts) faster
- departure: 3 min if proceeding aircraft is 40 kts faster
- levels crossed: 15 min (default), 10 min (regular fixes), 5 min (absolute minimum)
- on same NDB: more than 30 degrees at distance greater than 15 NM from facility
- same VOR: more than 15 degrees at distance greater than 15 NM from facility
- DME: 20 NM (10NM if 20 kts faster)

clearance to land: at the latest 2 NM from touchdown

no more speed control: 4 NM or less from touchdown

report significant wind changes:
- head: 10kts
- cross: 5kts
- tail: 2 kts

## AIP

GEN: Services, Sigmet, S and R, location indicators, fees, local regulations
ENR: communication failures, runway signals, holding/approach/departure procedures
AD: fueling, meterological information, runway lightning 

## Aeronautical information service AIS

- Movement area: manoeuvring area, aprons, maintenance stands
- apron: load and unload, parking, refueling, maintenance
- airside:

AIRAC: Advanced!

### Transponder

## Air Traffic Service ATS

> Insert Table

## Aerodroms

### Runway

### Lightning

### Signs

### Approach aids