on:
  push:
    paths: ['**.Rmd']

name: render-book

jobs:
  render-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-renv@v1
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("bookdown")'
        
      - name: Install devtools
        run: Rscript -e 'install.packages("devtools")'
      
      - name: Install emo
        run: Rscript -e 'devtools::install_github("hadley/emo")'
      
      - name: Render website
        run: Rscript -e 'bookdown::render_book()'
      
      - name: Commit results
        run: |
          git config --local user.email "oelschlaeger.lennart@gmail.com"
          git config --local user.name "Lennart Oelschlaeger"
          git add .
          git commit -m 'Rendered book' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
